### ISSUE TITLE
Filter slow pages

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Sloth#100]
Default to last month worth of data, then allow changing of filters

https://sloth.ucdavis.edu/payments/Transactions

https://sloth.ucdavis.edu/Jobs/KfsScrubberUpload (once per day)

https://sloth.ucdavis.edu/Jobs/CybersourceBankReconcile (once per hour)

Part 2: Make the details pages work.

**Comment by sprucely** [comment]
Filtering of transactions implemented in pull request #110 and merged to master.

**Comment by sprucely** [comment]
@srkirkland @jSylvestre The JobsController endpoint CybersourceBankReconcileRecords already has filtering parameters, but they are doubles and ints, and the code does a bunch of conversions between javascript ticks and C# datetimes...
https://github.com/ucdavis/Sloth/blob/9a45313f89e392fa53fc43f08f4fbebbbf4ab4a1/Sloth.Web/Controllers/JobsController.cs#L204-L240
It seems overly complex, and it doesn't appear the arguments are ever passed from anywhere within the application. Should I wipe it out and implement filtering/search like I did with Transactions?

**Comment by srkirkland** [comment]
I'm sure there's a good reason for it but I can't figure out why, or why it would be a big issue if we changed it.  I would agree it seems simpler to me if you update that logic to be more like what you did before.

**Comment by sprucely** [comment]
Figured it out. I was looking at the wrong controller action. The one above is to provide support for the calendar's ajax api. I'm going to rename it to be more clear.

**Comment by sprucely** [comment]
@srkirkland @jSylvestre It turns out that filtering on the Jobs pages shouldn't work exactly like the Transactions page. Using a daterange for a filter is not intuitive because what is displayed on the calendar's given month can span more than one datatable page, and what is displayed on a given datatable page can span more than one month. So it would probably end up with some unwieldy logic to keep the two views in sync.

Instead of a daterange, I think it would be better to use a "monthpicker" and only download data for a given month. Then all events displayed in the datatable are valid for the given month, and navigating to Prev and Next month is just a simple matter of reloading the page with a new month query parameter. This would also eliminate the need to populate the calendar via ajax, as the event data for the month can just be embedded in the page.

**Comment by jSylvestre** [comment]
@sprucely If you filter it by month, are you filtering the report date or when the report was run?
I *think* if you are filtering the report date, and also show all occurrences that it was run, that would be fine.

**Comment by sprucely** [comment]
@jSylvestre I'm not sure what a report date is. I'm filtering by ProcessedDate. I think the original code for calendar events was incomplete. It returned jobs with a ProcessedDate within a range and labeled all of them as `'event-success'`. For the moment, I have it labeling jobs with a status of `'Finished'` as `'event-success'` and everything else as `'event-info'`. Before creating a pull request, I'll look into mapping the various job statuses to relevant calendar event types.

**Comment by jSylvestre** [comment]
@sprucely There is a Date Processed and Ran on:

![image](https://user-images.githubusercontent.com/469010/80037577-b1c3e900-84a8-11ea-971b-80cf76f7d315.png)

**Comment by sprucely** [comment]
Yes, but what is a report date? ProcessedDate or RanOn?

**Comment by jSylvestre** [comment]
I believe the report date is the date of the cybersource report. RanOn is  when the job ran.
You can manually run the job for a specific date.
I didn't look at the table structure for it...

![image](https://user-images.githubusercontent.com/469010/80038084-b6d56800-84a9-11ea-80b8-2015b2ff72a2.png)

**Comment by sprucely** [comment]
@srkirkland For Part 2, did you have something specific in mind for the details pages? I could focus on document upload to azure blob storage and come back to this to provide a download link and/or embed them directly in the page.

**Comment by srkirkland** [comment]
@sprucely What I meant was they the query is really bad and about half the time the page seems to error out.  The last time I was debugging I had to scale up the database, not good.  I'm guessing it's a bad index or maybe some query join problem, or maybe a n+1 problem.   Feel free to close this out and make it a new issue though
