### ISSUE TITLE
Save into azure blob storage srubbers and CC reconcile docs

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Sloth#101]
Needs investigation.

Should save copies of downloaded reports for CC job.

If Scrubber job, should save uploaded scrubber, ex: https://sloth.ucdavis.edu/Jobs/KfsScrubberUploadDetails/c74d5628-8e7c-4b45-91f0-10a152e032b3

**Comment by sprucely** [comment]
I'm a little confused about the scrubber part. It appears it is already being saved to azure blob storage...
https://github.com/ucdavis/Sloth/blob/30143327a0b1395fdb225296313f09d7c959d3eb/Sloth.Core/Jobs/KfsScrubberUploadJob.cs#L67-L72
Is there some other container it should be stored in?

**Comment by jSylvestre** [comment]
@sprucely Maybe @srkirkland didn't mean the KFS scrubber but the CyberSource Reports?

**Comment by sprucely** [comment]
Oh, I see. That one was just an example.

**Comment by srkirkland** [comment]
@sprucely @jSylvestre I think the KFS upload service uploads the scrubber to KFS and has nothing to do with blob storage.

**Comment by srkirkland** [comment]
@sprucely  Yup, you can see in that snippet the FTP username and password.  Which is good but then it leaves us with no record of the file that was uploaded.  And as @jSylvestre notes, we do want the cybersource reports saved especially.  I'm ok with saving the KFS Scrubbers but I don't care much about that as a feature, since we can always regenerate them.  It's the CS Reports (those XML files) that I want saved.

**Comment by jSylvestre** [comment]
Might I suggest that the name contains both the report date and the run date?
Something like ReportDate{theDate/time}RunDate{the DateTime} ? Maybe a guid at the end so it will always 100% be unique?

That should make searching for it a little easier in the blob storage

**Comment by sprucely** [comment]
@srkirkland Okay, I'll focus on the CS Reports. But I wanted to point out that `_kfsScrubberService.UploadScrubber` does save to blob storage...
https://github.com/ucdavis/Sloth/blob/30143327a0b1395fdb225296313f09d7c959d3eb/Sloth.Core/Services/KfsScrubberService.cs#L48-L52

**Comment by srkirkland** [comment]
@sprucely oh, interesting.  Well then good -- is there any way to get to that from the site?

**Comment by srkirkland** [comment]
As far as the name goes, I actually think leaving the runDate off is better -- CS should have unique reports for a given ReportDate, no matter when you run it.  But really we should always be able to get to it from the site and hopefully never from blob storage itself

**Comment by sprucely** [comment]
@srkirkland Do you mean have the app/api retrieve it from blob storage as opposed to going directly through an Azure UI? Or do you mean it should already be stored in the DB?

**Comment by srkirkland** [comment]
> > @sprucely oh, interesting. Well then good -- is there any way to get to that from the site?
> 
> @srkirkland Do you mean have the app/api retrieve it from blob storage as opposed to going directly through an Azure UI? Or do you mean it should already be stored in the DB?

Yea, I mean is there a button on the website you can click to download/view the scrubber associated with a transaction.  I'm just wondering if that code saving the scrubber to blob storage is a one-way street.  It's not a big deal if it is, since scrubbers are easy to recreate compared to the CS reports, but that it how it would be most useful in the end.

**Comment by jSylvestre** [comment]
@sprucely @srkirkland It looks like it:
https://sloth-test.ucdavis.edu/payments/Scrubbers/Details/14b4d5ed-ffbe-4499-9ed0-4e7c05115147

**Comment by sprucely** [comment]
It's just model data from the DB.

**Comment by srkirkland** [comment]
Yea fake out, no way blob storage is integrated that well ;0

**Comment by sprucely** [comment]
I'll get back to this on Monday 2020/08/31, regardless of how close I am to completion on more fun projects =)
