### ISSUE TITLE
Tracking Number Columns Need Optimization

### ISSUE THREAD

**Issue by sprucely** [ucdavis/Sloth#109]
The current type for them is nvarchar(max) which is excessive and can be problematic with indexing.

**Comment by jSylvestre** [comment]
The Transaction.ProcessorTrackingNumber should be a Max of 22 characters, but... to be safe, we might not want to make it that small.

https://support.cybersource.com/s/article/What-is-the-CyberSource-Request-ID

There are some other fields that are varchar(Max) as well like status, they should also be reviewd.

**Comment by sprucely** [comment]
Fixed by PR #294
