### ISSUE TITLE
Another Webhook...

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Sloth#115]
This will only apply to registration integration at the moment (and is only on test)

The webhook only gets called when the report is processed.
If the report is processed and transactions are created, those transactions are skipped in the future. (You can only process them once, even if you download the report multiple times)

If the webhook fails, it can never be called again by running the report.

So... We need a way to call the webhook again without running the report. (The method in registration has a flag to indicate that the funds distributions have been done, so theoretically the hook can be called multiple times. safely)

https://github.com/ucdavis/Sloth/blob/master/Sloth.Core/Services/CyberSourceBankReconcileService.cs#L192

**Comment by sprucely** [comment]
The payload for the webhook is pretty simple. Should this be a new endpoint in JobsController, and a "Retry Webhook" button added to the CyberSourceBankReconcile view in Sloth.Web?

**Comment by jSylvestre** [comment]
@sprucely I'm not sure the best place for the button. Probably not the jobs controller.
Maybe here?:
https://sloth-test.ucdavis.edu/registration/Transactions/Details/58adf613-d0b2-442d-ab1f-b32c9881e850

I think that page should have the info you need.

**Comment by jSylvestre** [comment]
Or maybe another action next to the "i" if web hooks exist?

![image](https://user-images.githubusercontent.com/469010/84086665-41602100-a99d-11ea-97b3-8fdba650c0f2.png)

**Comment by srkirkland** [comment]
@sprucely @jSylvestre is this done or are you waiting to deploy it first?

**Comment by sprucely** [comment]
@jSylvestre You mentioned wanting to do a test using tracking number 5919976127006594903002. Can you go ahead and try it?

**Comment by jSylvestre** [comment]
Can also be tested with 
https://sloth-test.ucdavis.edu/registration/Transactions?trackingNum=20911
https://registration-test.azurewebsites.net/Transaction/Details/20911

**Comment by sprucely** [comment]
@jSylvestre Transaction 20911 cleared. Anything else you want to check on this before I close it?

**Comment by jSylvestre** [comment]
@sprucely Looks good to me. There are now 2 funds transfers on sloth as I would expect.
