### ISSUE TITLE
Improve tracking of Transaction status

### ISSUE THREAD

**Issue by sprucely** [ucdavis/Sloth#144]
Create a table to hold temporal data for transaction status changes. (ie: Status, ValidFromDate, ValidToDate)

Update logic or create a table trigger to maintain this temporal data. (@srkirkland What's your take on table triggers?)

**Comment by jSylvestre** [comment]
@sprucely I'm not a fan of table triggers.

**Comment by srkirkland** [comment]
I agree with @jSylvestre I could go my whole life without seeing another table trigger, they are nothing but trouble.
