### ISSUE TITLE
Update transaction details for AE

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Sloth#214]
ex: https://sloth-test.ucdavis.edu/aggie-enterprise/Transactions/Details/7dffb80b-6305-45c6-ae56-3a079b863d51.  Table should be replaced with a simpler table which just shows Amount, Direction, description, and huge COA.  The "ShowXML" should be removed for AE and instead show whatever relevant details are in the JournalRequest table (if it has a journal request).  This would probably just be what date the journal was sent, status, and maybe eventually we can throw in a JSON serialized version of the request.  That would be extra credit ;0).

**Comment by jSylvestre** [comment]
I created a new issue specific to showing the payload #217
