### ISSUE TITLE
Allow filtering by merchant or processor tracking number

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Sloth#227]
make the UI make it more obvious that clicking on those cells creates a filter.  Perhaps we even remove from list and make the filter action initiate from details page?

**Comment by sprucely** [comment]
@srkirkland @jSylvestre I'm not sure what this issue is talking about. Was it created before transaction rows were made clickable? I think the related transactions feature on the details page probably eliminates any need for this type of change to filtering.

**Comment by jSylvestre** [comment]
@sprucely Yeah, I think this was before those changes. Probably close it because you can't click on them anymore and searching for those shows related txns as well.
