### ISSUE TITLE
Add a notes field

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Sloth#232]
Add a notes field to transfers and/or transactions that does not get uploaded to AE, but may provide more info in Sloth?

**Comment by srkirkland** [comment]
@jSylvestre we do have the "Description" field, which is currently unused, or at least very rarely used.

**Comment by jSylvestre** [comment]
We use it a lot, but I don't think AE has a place for it.
Description = $"Funds Distribution INV {invoice.GetFormattedId()}".SafeTruncate(40)

I don't think we upload this to AE, so we can just keep using it.
