### ISSUE TITLE
Create generic job to track job runs

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Sloth#233]
We can leave the specific **JobRecords tables, but I'd like to create just a generic one `JobRecords`.  Every job can record runs to that table, and we'll filter via the UI.  For starters, the new AEJournalJob will use it, but more jobs are coming soon.

Fields:
Id
JobName
StartedAt
EndedAt (nullable)
Status
Details (max length string filled with custom JSON if needed.  Used for recording processedDate for Cybersource, and maybe stuff like # records processed, generic useful metadata)

Additionally, I'd like to know which job modified a given transaction.  Currently this is done with individual properties on the Transaction object, i.e. `KfsScrubberUploadJobRecordId`.  I think it'd be clearer to make a new glue table to many-to-many Transactions to the new JobRecords table.

Then, for example, a run of AEJournalJob will write a new JobRecord with an Running status, and then if during that run it uploads a new GL or moves the transaction to completed status, etc, it should add a `jobRecord.Transactions.Add()` reference so we can look that up later.

**Comment by sprucely** [comment]
Would it make sense for the many-to-many table to hold some details about what the job did with the given transaction? in case a job does different things based on, say, a transaction status?

**Comment by srkirkland** [comment]
> Would it make sense for the many-to-many table to hold some details about what the job did with the given transaction? in case a job does different things based on, say, a transaction status?

hmm, I do like this idea

**Comment by srkirkland** [comment]
Decision:

create `JobRecords` table as initially conceived.  Don't match job runs to TXNs, we'll use the regular transactionStatusEvents to record the needed modifications performed by jobs
