### ISSUE TITLE
optional required

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Sloth#234]
The transfer field ReferenceId is optional.
AE requires this. At least where we are putting it.
This field is not populated when CyberSource creates the transfers

**Comment by jSylvestre** [comment]
if is also 8 characters I think and we have a larger field in AE to put in.

**Comment by srkirkland** [comment]
@jSylvestre I labeled this with investigate since i'm not sure what we'll end up putting in there, and how the API will use that info once we move into the "GLIDE" batching strategy.  But if we do use it then we can look into expanding the field length.

**Comment by jSylvestre** [comment]
KFS tracking number is perfect. PR incomming

**Comment by srkirkland** [comment]
@jSylvestre still need this issue?
