### ISSUE TITLE
AE Stale Status

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Sloth#241]
A stale status from AE indicates that the transaction didn't make it to oracle.
We should treat these the same as error or rejected and resubmit with a new consumerTrackingId

**Comment by sprucely** [comment]
@jSylvestre Should the same transaction be updated and resubmitted? Or should it be marked as cancelled, and a new copy submitted?

**Comment by jSylvestre** [comment]
@sprucely I think updated and resubmitted. That way all the info is together in the timeline.
So, closing this one.
