### ISSUE TITLE
Tech work on design1

### ISSUE THREAD

**Issue by cydoval** [ucdavis/Sloth#245]
- [x] Hook up team choose form (remove teams from navigation, add disabled if can't change team?)
- [x] Fix dropdown toggle for profile? or just have it link to profile page(manage?)
- [x] Add team name to transaction Viewbag.Title
- [x] Hook up alert logic
- [x] Hook up all filter logic
- [x] Active class applied to navbar nav-link
- [x] Remove time from Transaction date column
- [x] Removal clickable merchant ID
- [x] remove the small search above the table -- Removed big search, but put placeholder in small search
- [x] Redirect to transactions index if only in 1 team
- [x] sorting of transactions. Column order changed, so double check column types are still good.
- [x] Add the "webhook" button from the transactions table to the details page
- [x] Clickable transaction rows to go to the details page
- [x] Fix DatePicker on CyberSource Job page. Other places?
- [x] Check if user has permissions to Approve on details page.

**Comment by jSylvestre** [comment]
@cydoval What did you need this for?
Add team name to transaction Viewbag.Title

That shows up as the selected team in the dropdown...
