### ISSUE TITLE
Transactions table - allow open in new tab

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Sloth#297]
https://sloth-test.ucdavis.edu/aggie-enterprise/Transactions

Clicking on a row takes you to that row, which is nice, but ctrl+click or right-click -> open in a new tab should work too.  Not sure the best way to do that, but my guess is each column needs the content wrapped in an anchor tag maybe?  That might break searching though so you'd have to see what the best option is.

But I think it's going to be useful to compare 2 or more txns and there isn't a good way to do that if you can't open in new tab

**Comment by cydoval** [comment]
https://github.com/ucdavis/Sloth/commit/bfdd51fa852a92058a6fd3efb568e3a558f16a85
