### ISSUE TITLE
Merchant Grouping

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Sloth#311]
Random idea for sloth.
Add an extra field like merchant tracking number: merchant grouping. For registration and payments this could be used to find/group transactions together (Event or team)
For devar, we could put in the allocation or something similar.

 —  metadata is pretty common on these type of systems.  cybersource has a bunch of merchant_defined_field_N cols, strip is just an arbitrary key/value.  So along with the txn you could send something like metadata: { allocation: 'xyz' } .   That could presumably then be grouped or searched by.
[3:34](https://ucdavis.slack.com/archives/G011R5HQ4DR/p1669937689315359)
adding in the data is one thing, and not terribly hard, but then surfacing it and letting people search or report by it is another.  but doable and probably a good idea, since we do have a slight disconnect now where people can put in a txn and we don’t store any additional metadata…. w/ KFS there were some additional fields they accepted in the scrubbers and we didn’t need them, but that is a bit limiting

**Comment by srkirkland** [comment]
solved by metadata
