### ISSUE TITLE
Email totals?

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Sloth#323]
KFS emails out amounts of money moved like this. Maybe we should have daily reports emailed out too?:

        Transmission Date: 2023-01-23

               Group Credits     = 00006              $949.46
               Group Debits      = 00004              $949.46
               Group Not C/D     = 00000                $0.00
               Valid Group Count = 00010              $949.46

********************************  Scrubber Summary Report  ********************************
* UNSCRUBBED RECORDS READ       : 10
* SCRUBBED RECORDS WRITTEN      : 10
* ERROR RECORDS WRITTEN         : 0
* EXPIRED ACCOUNTS FOUND        : 0
*******************************************************************************************

********************************  Demerger Summary Report  ********************************
* ERROR RECORDS READ                             : 0
* VALID RECORDS READ                             : 10
* ERROR RECORDS REMOVED FROM PROCESSING          : 0
* VALID RECORDS ENTERED INTO ORIGIN ENTRY        : 10
*******************************************************************************************

**Comment by srkirkland** [comment]
New REPORT: Daily Summary -- show grouped transaction status events by day for the last week. $$ completed, $$ rejected, etc, for a given day.  Optional - add datepicker to choose different week in past.
