### ISSUE TITLE
add a status color/badge for `Cancelled` status

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Sloth#339]
I think all of the other statuses have one already.   https://github.com/ucdavis/Sloth/blob/master/Sloth.Core/Resources/TransactionStatuses.cs

**Comment by sprucely** [comment]
@srkirkland Do you mean to change the existing badge color? Because `badge-cancelled` is already defined.
https://github.com/ucdavis/Sloth/blob/25295645e1877941f070ccfde82e0ed63ac25d5a/Sloth.Web/wwwroot/scss/components.scss#L62-L65

**Comment by sprucely** [comment]
Addressed by pr #340
